# For more inforamtion https://www.baeldung.com/spring-boot-yaml-vs-properties
spring:
  application:
    name: 'Respawn Hub'
    profiles:
      active: 'dev'
  profiles:
    active: 'dev'
rawg:
  endpoint: 'https://api.rawg.io/api'
  path: '/games'
  query: ''
  apikey: '?key='